//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authoservice.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }

        // Свойство для хранения состояния "выбран/не выбран"
        public bool IsChecked { get; set; }

        public SolidColorBrush ColorBrush
        {
            get
            {
                return (SolidColorBrush)(new BrushConverter().ConvertFromString($"#{Color}"));
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
    }
}
